name: Release
# Based on - https://github.com/developmentseed/lonboard/blob/main/.github/workflows/release.yml

# Only run on new tags starting with `v`
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build dist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.11"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.0
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: poetry install --no-root
      - name: Build dist
        run: poetry build
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/

  upload_pypi:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          # To test: repository_url: https://test.pypi.org/legacy/
